### PR TITLE
Dotenv deployment

### PR DESCRIPTION
**Pull request by chulkilee**
For non-heroku deployment.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://chulkilee-dotenv-deployment.23f39035947abfbf29f9f7741cb9c271.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by stevecrozz** [comment]
Regarding dotenv-deployment and capistrano 3:
"This gem is not needed; Capistrano 3 has a baked-in mechanism for symlinking files. Just add .env to the list of linked files, for example"
https://github.com/bkeepers/dotenv-deployment#capistrano-3

**Comment by chulkilee** [comment]
Right - it can be removed once Capistrano is upgraded to 3.

**Comment by stevecrozz** [comment]
@chulkilee are you using capistrano? would you like to do that upgrade for us?

**Comment by chulkilee** [comment]
@stevecrozz created #794.

Can we merge it and then upgrade capistrano?

**Comment by shingara** [comment]
maybe not usefull to merge it if you finish your capistrano upgrade PR ?

**Comment by chulkilee** [comment]
One of reason I want to merge it before the capistrano upgrade pull request is with this changes capistrano doesn't need to hande secret_token.rb.

**Comment by chulkilee** [comment]
Oh sorry not this one - I meant #778. So order should be #778, #794 then this #787

**Comment by chulkilee** [comment]
Moved to #778 since that requires this change.

**Pull request closed without merging**
