### PR TITLE
Fix webhook to actually send its body

### PR DESCRIPTION
**Pull request by douglaswth**

### CODE REVIEW

**Comment by stevecrozz** [comment]
Thanks @douglaswth . That's a pretty surprising bug. My only question is, does this work correctly even though we seem to be not setting the Content-Type header to 'application/json' ?

**Comment by douglaswth** [comment]
Sort of, in that my application probably isn't checking the content-type header at the moment. I can add that as well if you like.

**Comment by stevecrozz** [comment]
Awesome. Thanks for the fix!

**Comment by stevecrozz** [comment]
The rubocops got you

**Comment by douglaswth** [comment]
@stevecrozz Also, do you have access to make a new release of Errbit to DockerHub? It doesn't look like it has been updated in 9 months: https://hub.docker.com/r/errbit/errbit/tags.

**Comment by stevecrozz** [comment]
I made a v0.9.0 release today

**Comment by floehopper** [comment]
Correction:

> I made a ~v0.9.0~ v0.8.0 release today

**Pull request merged**
