### PR TITLE
Updated #865 - Redesign with bootstrap

### PR DESCRIPTION
**Pull request by mattclements**
Updated version of #865 with the minor fixes that were required merged in - happy to pick this up to get this over the line so let me know if it needs any tweaks!

### CODE REVIEW

**Comment by stevecrozz** [comment]
Thanks for picking this up @mattclements. I'll take another look soon. I do love bootstrap, but I also want to make sure that what we end up merging is at least as good usability-wise with what we already have. So I'll be looking to squash any regressions before we hit the merge button. Last time I looked, for example, there were some major usability issues on smaller windows.

**Comment by mattclements** [comment]
I totally agree @stevecrozz - I am using this with my team now; and therefore I will probably receive some feedback from them during the course of testing this.

Likewise if you have any comments/suggestions please let me know and I can tweak.

**Comment by stevecrozz** [comment]
@mattclements I just took this design for a quick spin. I'm pretty excited about the progress here, but I found two things I really want to change before we merge this. Do you mind having a look?
http://youtu.be/6xakbjBZ0nc

**Comment by mattclements** [comment]
Thanks @stevecrozz - Still some work to be done; but I have added a little fix which should sort out the responsive view a little :+1:

**Comment by rigor789** [comment]
I support the idea of bootstrap, and I think it should have a sidebar menu similar to [AdminLTE](https://almsaeedstudio.com/preview) I really like the way it acts on small devices, and it just feels right!

**Comment by toshimaru** [comment]
:+1:

**Comment by epintos** [comment]
Any update on this?

**Comment by nofxx** [comment]
Waiting for this beauty!

**Comment by stevecrozz** [comment]
It would still be good to have this, but there are still some issues to work out. If any of you folks want to put some effort into this story, I'd be happy to have the help. The issues I found are summarized my comment on Jun 26 above (https://github.com/errbit/errbit/pull/903#issuecomment-115901075)

Additionally, the source branch has fallen behind master to the point where it now has conflicts so those will have to be resolved as well before we can merge this. @mattclements are you intending to do this work or would you like to see if someone else wants to pick it up?

**Comment by stevecrozz** [comment]
It seems like this effort is fading away. I'm going to close it, but I believe we'll have a new UI some day.

**Comment by rjhancock** [comment]
I might have a go at this. As I write more apps I've been using Errbit more so might as well contribute something to it.

I'll start fresh though from current master.

Any suggestions on changes besides just moving to Bootstrap 3?

**Comment by stevecrozz** [comment]
@rjhancock Might as well start with bootstrap 4 at this point :)

But actually, I think the prior efforts have fallen through because of size/complexity. If you find anything that can be done to prepare for the change as an independent task, I think that would help a lot towards a successful outcome. For example, I recently introduced font-awesome on its own so that's one less thing to account for during the big redesign. I'm not sure if there are more tasks like that, but its a win if you can find any.

**Comment by stevecrozz** [comment]
Also if you want to kick some ideas around, we can do that in https://gitter.im/errbit/errbit

**Pull request closed without merging**
