### PR TITLE
upgrade capistrano to 3.4.0

### PR DESCRIPTION
**Pull request by chulkilee**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://chulkilee-capistrano-3-4.23f39035947abfbf29f9f7741cb9c271.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://chulkilee-capistrano-3-4.23f39035947abfbf29f9f7741cb9c271.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by arthurnn** [comment]
@chulkilee did you test the deploy script still works? I dont use capistrano, so I dont have any errbit app I can test this.
thanks

**Comment by jlecour** [comment]
I might be able to try this next week, on my fork.

**Comment by chulkilee** [comment]
It works on my case.

**Comment by arthurnn** [comment]
thanks

**Pull request merged**
