### PR TITLE
Remove capistrano as a supported deploy mechanism

### PR DESCRIPTION
**Pull request by rud**
As mentioned in https://github.com/errbit/errbit/issues/1230#issuecomment-355782125 the capistrano deployment mechanism is going away in the future. 

This PR does the work of actually removing the dependency, documentation, and unsupported sample config.

### CODE REVIEW

**Comment by stevecrozz** [comment]
I was just thinking about this same thing @rud, prompted by the new gem update nag bot which is probably the same reason you're doing this. I know people did use capistrano in the past. I guess nothing stops the same people from continuing to use capistrano even when we remove it from the Gemfile.

Even so, maybe we should leave this open for a week or so and make sure we don't get a lot of objections.

**Comment by rud** [comment]
If this is merged, fixes #1301

**Comment by rud** [comment]
Rebased on master

**Comment by rud** [comment]
Alright, it's a week later, the build is fully green after a rebase, the code will stay around in the git history. I'm pushing the merge-button. 🚀

**Pull request merged**
