### PR TITLE
Use puma instead of unicorn

### PR DESCRIPTION
**Pull request by otzy007**
unicorn gem and configs have been replaced with puma configs found on https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server

I've removed unicorn from documentation too and the capistrano deploy script has been updated to deploy with puma using the capistrano3-puma gem.

I've tested the deployment on heroku and with capistrano on a ruby:2.2 docker container.

This is a PR for #999

### CODE REVIEW

**Comment by stevecrozz** [comment]
Looks great! it's worth noting that this change not only replaces unicorn with puma, but also changes the application container model from pure workers to workers + threads. Having the ability to do this easily is one of the reasons I like puma, but it also has the potential to expose issues we haven't yet had to deal with such as https://github.com/errbit/errbit/issues/978

We can deal with those if they appear. I think its time.

**Comment by stevecrozz** [comment]
@otzy007 Would you mind updating the docs in ./docs/deployment/capistrano.md to reflect your changes?

**Comment by stevecrozz** [comment]
One other thing is the unicorn_worker_killer. We still have configuration in .env.default such as KILL_ON_RSS_MIN=250 which is useful for killing unicorn processes that exceed certain resource limitations. If we can maintain this functionality, that would be awesome. Otherwise we should dump these configuration parameters.

**Comment by otzy007** [comment]
@stevecrozz ok. I'll take care of the capistrano documentation and I'll check if puma needs or has some kill options.

**Comment by otzy007** [comment]
I've updated the docs and the capistrano template.
About the KILL_ON_RSS_MIN, puma doesn't have such a feature. Correct me if I'm wrong please.
It has just this timeout config https://github.com/puma/puma/blob/master/examples/config.rb#L155

From my past experience with puma I've been monitoring the process with monit to check if it has crashed or it's exceeding an imposed limit of RAM.

So. Should I dump those KILL_ON_RSS ?

**Comment by stevecrozz** [comment]
I think you're right @otzy007. And I think these KILL_ON params all need to go. If you take a look through https://github.com/errbit/errbit/pull/990 you should be able to spot all the changes. It'll be a minor bummer for @8398a7, but I think the benefits of puma outweigh the lack of worker killer.

Maybe we can consider https://github.com/xeger/stalin or link to some docs on setting up monit in the future.

**Comment by otzy007** [comment]
Monit is pretty straight forward. There's a capistrano task to upload the config. You just have to edit the config if you want to limit the memory usage.

Stalin looks good too, but what if puma crashes? Monit will restart it, but stalin is unable. In the past for me puma crashed a few times on rubinius or jruby

**Comment by otzy007** [comment]
Here are the docs for monit 😎 d902148e1ba87e2c6f2f908993348965c9b88a42

**Comment by stevecrozz** [comment]
Thanks @otzy007. This is looking really good!

I have a couple last questions/notes:
- Why port 3000? It looks like in the past we used 8080 and I don't see the reason for the change
- puma can live in the regular non-production section of the Gemfile unless you see a reason it shouldn't. I plan to run puma for both development and production
- should we consider using the default capistrano-puma puma.rb template for capistrano deployments? https://github.com/seuros/capistrano-puma/blob/master/lib/capistrano/templates/puma.rb.erb (can be generated as part of the `rails generate capistrano:nginx_puma:config` generator)

**Comment by otzy007** [comment]
1. Ok. I'm changing to 8080. 3000 was into the example config from heroku that I've copy-pasted mostly
2. OK :) Actually even if you set  puma under the production group `rails s` will start with puma
3. Yes.  puma.rb config is generated by capistrano based on the settings on deploy.rb for capistrano deployments. I've just forgot to remove the symlink.

One more thing. With the capistrano deployment puma is started without workers using the default setting and with the default number of threads (0, 16). On JRuby workers are not available.

**Comment by stevecrozz** [comment]
It makes sense that workers are not available in JRuby. Since JRuby can make much better use of multiple cores, there's a lot less reason to run multiple workers. I'm good with the capistrano-puma defaults because I'm sure users will end up customizing config/deploy.rb to suit their own needs.

This seems to be ready to go. I'm thinking of releasing one final version of Errbit before merging this PR because this is a substantial change for those of us who are used to deploying unicorn.

**Comment by otzy007** [comment]
Great. Thank you 😀

**Comment by stevecrozz** [comment]
@otzy007 I'm prepping the v0.6.0 release and this is the first thing I plan to merge after that. But the PR has acquired conflicts. Can you resolve them over the next day or two? If not, I can probably tackle it too.

**Comment by otzy007** [comment]
Sure. I'll rebase it tomorrow

**Comment by otzy007** [comment]
it's ready to be merged now 😃

**Comment by stevecrozz** [comment]
done. thanks once again @otzy007 !

**Comment by otzy007** [comment]
I'm glad I can help 😃

**Pull request merged**
