### PR TITLE
update deployment docs with env-config instructions

### PR DESCRIPTION
**Pull request by stevecrozz**
Heroku changes are pretty straightforward, but I tested capistrano deployment for the first time and found it to be lacking in both functionality and documentation. For example, I found no existing way to actually start the application using capistrano, so I added a task for that.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://stevecrozz-update-deployment-config.23f39035947abfbf29f9f7741cb9c271.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://stevecrozz-update-deployment-config.23f39035947abfbf29f9f7741cb9c271.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by arthurnn** [comment]
This make sense @stevecrozz , lets merge this, and people will let us know if something is not working anymore.
I also dont use capistrano, so it is hard for me to test.

thanks btw.

**Comment by stevecrozz** [comment]
Sure no prob. I'll get this merged in. I did test it by deploying it to my own laptop, so we should hopefully be good. I wonder if we can design some sort of integration test for this capistrano stuff. Let me know if you have any ideas.

**Comment by arthurnn** [comment]
Capistrano tests are always hard. I never were able to test them to be honest.

**Pull request merged**
