### PR TITLE
Update gem uglifier in order to avoid security vuln as reported by gemnasium

### PR DESCRIPTION
**Pull request by compwron**
https://gemnasium.com/errbit/errbit 
screen shot 2015-12-01 at 5 12 07 pm

### CODE REVIEW

**Comment by stevecrozz** [comment]
Why did you include a change to .gitignore?

**Comment by compwron** [comment]
In order to ignore the bin directory, where binstubs are stored, which do not appear to have been  previously tracked in version control. https://robots.thoughtbot.com/use-bundlers-binstubs

**Comment by stevecrozz** [comment]
Can you exclude that change from the PR? It seems like the Rails recommendation is to add any binstubs you find useful to the ./bin folder and check them into source control:
http://api.rubyonrails.org/v4.2.0/classes/Rails/AppRailsLoader.html

**Comment by compwron** [comment]
Ok I took it out :)

**Comment by stevecrozz** [comment]
Thanks for keeping an eye on the Gemfile!

**Pull request merged**
