### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by Rovel**
Update docker image from ruby 2.5.1-alpine to match app.json ruby version

### CODE REVIEW

**Comment by stevecrozz** [comment]
That coverage report doesn't make any sense so I'm merging this.

**Comment by Rovel** [comment]
nice! thks

r u guys open to a new UI style?

**Comment by stevecrozz** [comment]
Yeah, a new UI would be great. There have been several attempts at this already, but I think they have all been too ambitious. I think in order to make progress we need someone who really wants to lead this effort by organizing a number of smaller, individual projects. Like we could start by building new tables, then new forms, then new dialogs, then new navigation, etc.

Doing it all at once seems to be too much. But I'm happy to talk it over if you are interested.

**Comment by Rovel** [comment]
sure, let me open a issue

**Pull request merged**
