### PR TITLE
Be consistent by always using error(s).

### PR DESCRIPTION
**Pull request by WouterSioen**
"Error(s)" and "Err(s)" where mixed up in the translations.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://woutersioen-patch-1.23f39035947abfbf29f9f7741cb9c271.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://woutersioen-patch-1.23f39035947abfbf29f9f7741cb9c271.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by stevecrozz** [comment]
It looks like there are some tests that are looking for specific text that is changed here. This is a nice change, but we can't merge it until the tests are passing.

**Comment by WouterSioen** [comment]
I'll look into it

**Comment by WouterSioen** [comment]
Looks like the tests are passing again :)

**Comment by stevecrozz** [comment]
Thanks for this

**Pull request merged**
