### PR TITLE
#553 document deploy hooks

### PR DESCRIPTION
**Pull request by stevecrozz**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://stevecrozz-553-document-deploy-hooks.23f39035947abfbf29f9f7741cb9c271.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by shingara** [comment]
Good. But you can say it's become with capistrano too.

**Comment by stevecrozz** [comment]
@shingara Do we have some special capistrano support?

**Comment by stevecrozz** [comment]
Ah, you must be talking about this:
https://github.com/airbrake/airbrake/blob/master/lib/airbrake/tasks/airbrake.cap

I'll add some docs on how to use the capistrano task.

**Pull request merged**
