### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by nacengineer**
Add the missing closing tags on the descriptive list in the Readme file

### CODE REVIEW

**Comment by stevecrozz** [comment]
This is fine with me, but just out of curiosity, is this causing a problem? I thought that HTML5 allowed for dd tags to be unclosed.

**Comment by nacengineer** [comment]
hmm. Well I'm trying to parse it with [this library](https://github.com/pragdave/earmark) for an internal application that fetches Readme's via Gitlab API. So maybe it's actually an issue with the parser. 🤔

**Comment by stevecrozz** [comment]
Probably, but if its causing you trouble, I'm fine with making this change.

**Comment by nacengineer** [comment]
ty! 👍🏻

**Pull request merged**
