### PR TITLE
Fix Slack Integration Service

### PR DESCRIPTION
**Pull request by jules2689**
The issue
---
 - It seems that Slack stopped using the url format previously specified `https://#{subdomain}.slack.com/services/hooks/incoming-webhook?token=#{api_token}`

The fix
---
 - Instead what is now being used is the Slack Integration for Airbrake.
   - This provides the end user with a hook url (service url) in the following format `https://hooks.slack.com/services/XXXX/XXXX/XXXX`
   - They encourage this to be copied directly into Airbrake, so I figured this would be better to do with Errbit as well.

I've tested this on my local Errbit instance with great success :)

cc @arthurnn for review?

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://jules2689-master.23f39035947abfbf29f9f7741cb9c271.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://jules2689-master.23f39035947abfbf29f9f7741cb9c271.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by jules2689** [comment]
No idea why this is conflicting, master is up to date.

**Comment by stevecrozz** [comment]
Without this change, slack notifications are broken?

**Comment by jules2689** [comment]
From what I could tell, yes. I could not find an option in Slack to provide me with an API Token such that the old slack service could function. I tried: Incoming Webhook & Airbrake, both provided a url similar to the one in the description.

The moment I switched to this however, everything worked.

**Comment by jules2689** [comment]
Related: https://github.com/errbit/errbit/issues/756
They seem to indicate the last numbers as the "API Token", however myself and another in that thread could not get that to work.

**Comment by stevecrozz** [comment]
We should make this change then. I've had a small concern that this would break for anyone who has these notifications all set up and working the old way, but there's not much we can easily do for them. Thanks for this, and thanks for the added docs! Will merge momentarily.

**Comment by jules2689** [comment]
I considered that as well, but I'm wondering if its even working for them at this point in time.
Bonus is that this is a lot easier to setup, and requires only one field.

**Pull request merged**
