### PR TITLE
README: Serve images on https

### PR DESCRIPTION
**Pull request by szepeviktor**
https://github.com/errbit/errbit/raw/gh-pages/

### CODE REVIEW

**Comment by szepeviktor** [comment]
There is a BitBucket failure for https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2

See https://www.google.com/search?q=phantomjs-2.1.1-linux-x86_64.tar.bz2+is+not+a+bzip2+file

**Comment by ecaron** [comment]
Should these reference https://raw.githubusercontent.com/errbit/errbit/gh-pages/images/ instead of https://github.com/errbit/errbit/raw/gh-pages/images/?

**Comment by szepeviktor** [comment]
I think we should get the URL from the <kbd>Raw</kbd> button.

**Comment by stevecrozz** [comment]
Hey @ecaron and @szepeviktor is this mainly about https on errbit.com? You may be interested to see what I'm working on at: https://github.com/errbit/errbit/issues/1154
https://errbit.com/

**Comment by szepeviktor** [comment]
> I'm working on at: #1154

Thank you.

**Pull request closed without merging**
