### PR TITLE
Use Ruby 2.3.3 by default

### PR DESCRIPTION
**Pull request by tricknotes**
It seems a stable release of Ruby 2.3.x.

### CODE REVIEW

**Comment by tricknotes** [comment]
The broken spec on Ruby 2.2 will be fixed by https://github.com/errbit/errbit/pull/1142

**Comment by stevecrozz** [comment]
Thanks @tricknotes. I merged the other branch.

**Comment by tricknotes** [comment]
Thanks @stevecrozz !
I'll rebase to resolve conflict with #1142 .

**Comment by tricknotes** [comment]
> I'll rebase to resolve conflict with #1142 .

done.

**Comment by stevecrozz** [comment]
cheers!

**Pull request merged**
