### PR TITLE
Fix some low hanging rubocop issues

### PR DESCRIPTION
**Pull request by rud**
This builds on #963, most of these commits are already included there. 

I'm going to chip away at the `.rubocop_todo.yml` file for a bit here, changing as little as possible while hopefully making both rubocop, code climate, and the maintainers happy.

### CODE REVIEW

**Comment by stevecrozz** [comment]
I really appreciate this effort. I'll be happy to merge this. But will you first squash these commits into just one or a small handful of logical chunks?

**Comment by rud** [comment]
Hi @stevecrozz,

Thank you for your feedback, much appreciated. I can certainly squash these, though then reviewing becomes quite a bit more tricky when a bunch of stuff is modified in a single commit. I've taken pains to keep stuff separate to ease the burden on the reviewer - I personally think gigantic commits are problematic. These are separate changes, each focusing on fixing a single systemic issue as classified by rubocop, some fixed by hand, some automatically. 

I could easily strip out the "regenerate TODO file" commits, those are not super valuable, outside of documenting things getting better over time. I'll try that first :)

**Comment by rud** [comment]
Focusing on  #963 first.

**Comment by rud** [comment]
Thank you for merging #963. I've now rebased and squashed a few of these commits, hopefully they are still easy enough to review. Let me know if there's more I can do to ease the review.

Thanks!

**Comment by rud** [comment]
Alright, let's call it a day here, all set for final review :)

**Comment by stevecrozz** [comment]
Sounds good. I'm ready to merge it. Great work.

**Comment by rud** [comment]
:cake:

**Pull request merged**
