### PR TITLE
Fix Google authentication due the sunset of Legacy People API

### PR DESCRIPTION
**Pull request by juliogc**
# The problem

The omniauth authentication flow for Google accounts uses a legacy API (called [Legacy API Documentation](https://developers.google.com/people/legacy)) that was officially discontinued on March/7/2019 and Google is still keeping it alive just to avoid brake the old Google API projects

For new Google API projects we have to use the new [People API](https://developers.google.com/people/api/rest) but the current version from **omniauth-google-oauth2** used on the project is not compatible with this Google's change and completely breaks the Google's authentication flow from applications that uses a brand new Google API project.

In short, without this update no new Google API projects will be able to setup Google authentication flow in Errbit

## Evidences
```Started GET "/users/auth/google_oauth2" for ::1 at 2020-04-01 16:24:41 -0300
(google_oauth2) Request phase initiated.
Started GET "/users/auth/google_oauth2/callback?state=34089bc3393425a490b4f0dc8f87a38b854d8a4da30d42f4&code=4/yAEmleX2eiaBJvznrA1JCAa1ujER_7djlNcqsCddShEjRx5_KJi-0inF0FJ-SIavB7J7gart9m2dbuIzEYtISWE&scope=email%20profile%20https://www.googleapis.com/auth/userinfo.email%20https://www.googleapis.com/auth/userinfo.profile%20openid&authuser=1&hd=bionexo.com&prompt=none" for ::1 at 2020-04-01 16:24:47 -0300
(google_oauth2) Callback phase initiated.
(google_oauth2) Authentication failure! invalid_credentials: OAuth2::Error, {"code"=>403, "message"=>"Legacy People API has not been used in project 382088683903 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/legacypeople.googleapis.com/overview?project=382088683903 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.", "status"=>"PERMISSION_DENIED", "details"=>[{"@type"=>"type.googleapis.com/google.rpc.Help", "links"=>[{"description"=>"Google developers console API activation", "url"=>"https://console.developers.google.com/apis/api/legacypeople.googleapis.com/overview?project=382088683903"}]}]}: 
{
  "error": {
    "code": 403,
    "message": "Legacy People API has not been used in project 382088683903 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/legacypeople.googleapis.com/overview?project=382088683903 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.Help",
        "links": [
          {
            "description": "Google developers console API activation",
            "url": "https://console.developers.google.com/apis/api/legacypeople.googleapis.com/overview?project=382088683903"
          }
        ]
      }
    ]
  }
}

Processing by Users::OmniauthCallbacksController#failure as HTML
  Parameters: {"state"=>"34089bc3393425a490b4f0dc8f87a38b854d8a4da30d42f4", "code"=>"4/yAEmleX2eiaBJvznrA1JCAa1ujER_7djlNcqsCddShEjRx5_KJi-0inF0FJ-SIavB7J7gart9m2dbuIzEYtISWE", "scope"=>"email profile https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile openid", "authuser"=>"1", "hd"=>"bionexo.com", "prompt"=>"none"}
Redirected to http://localhost:6543/users/sign_in
```

# The solution proposal

To fix this issue, I'm submiting this change that updates omniauth-google-oauth2 to `0.7.0` version.

# Notes

This change is not intended break the olds Legacy People API flows once the new People API grant compatibility. 

# More infos

- [Legacy API Documentation](https://developers.google.com/people/legacy)
- [People API](https://developers.google.com/people/api/rest)
- [Rails Google Oauth2 - Legacy People API has not been used in project](https://stackoverflow.com/questions/59570678/rails-google-oauth2-legacy-people-api-has-not-been-used-in-project)

### CODE REVIEW

**Comment by stevecrozz** [comment]
Looks good @juliogc! Thanks for the contribution and all the info.

**Comment by juliogc** [comment]
@stevecrozz Thank you so much!

There are any prevision when it will come in a release tag? I'm expecting to use Errbit in official docker image instead to build mine

**Comment by stevecrozz** [comment]
There is no official policy on how often we release but I'm thinking I should write one because we are getting that question somewhat frequently. I've tended to do releases only when there are significant changes, or enough small ones to add up to something significant. Maybe we can settle on something more time-based, like 6 month release intervals as needed.

**Comment by juliogc** [comment]
Thanks for explaining! For while I'll provide a custom build e keep waiting for the release.

**Pull request merged**
