### PR TITLE
upgrade to rspec 3

### PR DESCRIPTION
**Pull request by stevecrozz-**

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://stevecrozz-rspec3.23f39035947abfbf29f9f7741cb9c271.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by arthurnn** [comment]
will look into that. thnkas

**Comment by stevecrozz** [comment]
Actually. Looks like everything is running smoothly now. I'm just trying to get rbx to run as well as it used to.

**Comment by stevecrozz** [comment]
This is ready to go from my perspective.

**Comment by arthurnn** [comment]
LGTM .. good job ! :shipit: !

**Pull request merged**
