### PR TITLE
Fix favicon URL

### PR DESCRIPTION
**Pull request by felixbuenemann**
Without this change the url points to /images/favicon.ico, which does not exist.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://felixbuenemann-fix-favicon.23f39035947abfbf29f9f7741cb9c271.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by arthurnn** [comment]
good catch

**Comment by arthurnn** [comment]
But I wonder if we should actually move the favicon to that location, so sprockets can digest that file ?!?

**Comment by felixbuenemann** [comment]
There are pros and cons. If you don't have a /favicon.ico you will get lot's of 404s from user agents that are trying to directly fetch the favicon without looking at the headers. On the other hand invalidating a non-digested favicon across browsers is very hard. If you want the best of both worlds, move the favicon to app/assets/images and symlink it to public.

If you prefer that way, I can push a new commit.

**Comment by arthurnn** [comment]
good idea... lets do the symlink dance.

**Comment by felixbuenemann** [comment]
OK, moved favicon to app/assets/images and added a symlink in public.

**Comment by arthurnn** [comment]
thanks

**Pull request merged**
