### PR TITLE
fixes problem in Issue#982 

### PR DESCRIPTION
**Pull request by meh-**
fixes problem in Issue#982 "This error has occured 0 times" instead of 1 time.

### CODE REVIEW

**Comment by stevecrozz** [comment]
Thanks @meh- 

This is probably the right place to make a change, but theoretically it should not be necessary to reload the document because we already return it in Problem.cache_notice (https://github.com/errbit/errbit/blob/1ad440bd3bedc406029478c2201d61316172925c/app/models/problem.rb#L105)

It would be good to avoid this extra database query for performance reasons.

**Comment by meh-** [comment]
ok, may be something like 
@problem = Problem.cache_notice(@error.problem_id, @notice)
@notice.problem = @problem

**Comment by stevecrozz** [comment]
Yeah that could work, but if possible I think it would be good to avoid that second line and stop accessing @notice.problem wherever we're doing that. Instead access @problem directly.

**Comment by stevecrozz** [comment]
Thanks @meh- I was coming back to this just now and noticed the issue is no longer present. I think some other fix must have taken care of this problem.

**Pull request closed without merging**
