### PR TITLE
Add syslog functionality

### PR DESCRIPTION
**Pull request by crunis**
@stevecrozz this adds the syslog functionality but something seems wrong since some output is still replicated in STDOUT. You may want to take a look.

### CODE REVIEW

**Comment by stevecrozz** [comment]
This looks good. Can you move the require statement inside the elsif block so that file is only required when needed?

Then it's probably time to document this parameter. Would you mind adding docs on ERRBIT_LOG_LOCATION to ./docs/configuration.md?

**Comment by crunis** [comment]
@stevecrozz : Done !

**Comment by stevecrozz** [comment]
Almost ready. The default is STDOUT, not no logging. The defaults are all here btw: https://github.com/errbit/errbit/blob/master/.env.default

**Comment by crunis** [comment]
fixed

**Comment by stevecrozz** [comment]
looks good. thanks for the contribution!

**Pull request merged**
