### PR TITLE
no need for wrapper gem, airbrake can easily be configured to send info ...

### PR DESCRIPTION
**Pull request by espen**
...about current user

### CODE REVIEW

**Comment by stevecrozz** [comment]
Interesting. It looks like you're right. I'll have to give it a shot and if it works the same as airbrake_user_attributes, then we can probably just remove this section since the airbrake gem docs cover this.

**Comment by espen** [comment]
Can confirm this is working on my install (latest errbit master)

**Comment by stevecrozz** [comment]
This makes sense. Thanks for checking that out. Since there's nothing our users need to do, I'm just going to remove this section from the docs.

**Comment by espen** [comment]
I think it's good to mention it in the docs (like with my PR). Even though it is a part of the Airbrake gem it is also a feature in Errbit.

**Comment by stevecrozz** [comment]
Ok. This sounds good, but I was too slow in merging your change. Can you rebase it onto master?

**Comment by espen** [comment]
Ok, done.

**Comment by stevecrozz** [comment]
did you push it?

**Comment by stevecrozz** [comment]
ah there it is, thanks @espen

**Pull request merged**
