### PR TITLE
incorrect namespace for rake task in docs

### PR DESCRIPTION
**Pull request by stephancom**

### CODE REVIEW

**Comment by stevecrozz** [comment]
Nice. Thanks for the catch. Although this incorrect text seems to appear elsewhere. Would you like to change the other references as well?

**Comment by stephancom** [comment]
I'll try to get to it soon :)

**Comment by stephancom** [comment]
appears to be done - was also referenced in another rake task

**Comment by stevecrozz** [comment]
Thanks @stephancom

**Pull request merged**
