### PR TITLE
add /problems?exclude_apps=app1,app2 feature

### PR DESCRIPTION
**Pull request by burnettk**
...to make problems page usable with noisy apps

this is the other half of #1273 , which i am declining since i did a rebase and added a bunch of commits that i didn't want somehow.

### CODE REVIEW

**Comment by stevecrozz** [comment]
I do want better filtering and I think this option is useful, but I'd like to consider it as part of a more ambitious filtering scheme. I'm inspired by the filtering options we use right here on github issues. Here's an example of a filter + exclusion search: https://github.com/errbit/errbit/issues?utf8=%E2%9C%93&q=author%3Astevecrozz+-label%3Abug+

@burnettk: Can you think of a way to add the app exclusion filter you want while working toward a future where we have a coherent filtering grammer like github's?

The first thing that comes to my mind is a search like `-app:app1 -app:app2`. Does that seem reasonable?

**Comment by burnettk** [comment]
did it!

**Comment by stevecrozz** [comment]
Seems good @burnettk. Not sure what's going on with Coveralls, but all the new lines you added are covered, so that shouldn't be an issue.

**Comment by rud** [comment]
Cool, merging

**Pull request merged**
