### PR TITLE
Rubocop cleanups - it's time

### PR DESCRIPTION
**Pull request by rud**

### CODE REVIEW

**Comment by stevecrozz** [comment]
Very awesome. I need a bit of time to review it, but this is looking great.

**Comment by rud** [comment]
All out of steam here, happy reviewing, hoping each commit is sufficiently focused.

**Comment by rud** [comment]
Is there anything I can help with here, or is it simply too many changes for a single pull-request? I can most certainly split it into smaller bits if that is at all helpful.

**Comment by stevecrozz** [comment]
This is fine. I've just been on vacation. Thanks again.

**Comment by rud** [comment]
@stevecrozz awesome, thank you! :airplane:

**Pull request merged**
