### PR TITLE
Refs #959 set rails env=test for test rake tasks

### PR DESCRIPTION
**Pull request by stevecrozz**

### CODE REVIEW

**Comment by md5** [comment]
I don't think `default` needs to be listed. I'd probably also check `top_level_tasks.any? { |t| test_env_rake_tasks.include? (t) }`

Otherwise, this looks great.

**Comment by stevecrozz** [comment]
Sweet. I made those changes and I think this is good. I'm gonna merge it.

**Comment by md5** [comment]
Looks like I spoke too soon about removing `default`. I've opened #1029 to add `default` to `test_env_tasks`.

**Comment by stevecrozz** [comment]
No prob

**Pull request merged**
