### PR TITLE
more I18n and pt-BR translations

### PR DESCRIPTION
**Pull request by rcnetto**
The current internationalization keys weren't enough to allow a full translation of Errbit. I added all the missing keys and their corresponding pt-BR translation. The rails.pt-BR.yml was introduced to translate "time in words" functions. All tests passed with success.

### CODE REVIEW

**Comment by stevecrozz** [comment]
Very awesome. I'll give it a try!

**Comment by stevecrozz** [comment]
I had to add to my config/application.rb.
```ruby
config.i18n.available_locales = ["pt-BR"]
config.i18n.default_locale = :'pt-BR'
```

Is there an easier way? should we document this?

**Comment by rcnetto** [comment]
I think it's a good idea documenting it. It was not obvious to me (non ruby developer) how to do that. : )

**Comment by stevecrozz** [comment]
I'll put that on my list for documentation, but I don't see that as a reason to keep from merging this. Thanks very much!

**Pull request merged**
