### PR TITLE
Heroku deploy: add demo data too

### PR DESCRIPTION
**Pull request by rud**
Status: user/password is now set correctly. No demo data yet.

### CODE REVIEW

**Comment by rud** [comment]
Closing to have heroku app destroyed so it can be recreated.

**Comment by rud** [comment]
Re-opening to re-deploy

**Comment by rud** [comment]
Think this is ready to test - at least the demo admin user is created correctly. 

@stevecrozz I think you need to look in the Heroku logs to figure out why the `errbit:demo` rake-task doesn't seem to have any effect. That data is not created as far as I can tell.

**Comment by rud** [comment]
Btw, the `heroku_pr_review_app?` method in the seed file takes care of the special case of a Heroku deploy from a PR, unlike a regular deploy using the "Deploy to Heroku" button.

**Comment by stevecrozz** [comment]
Here's what I'm seeing from the build:
screenshot-dashboard heroku com-2018 08 05-17-31-13
[build-log.txt](https://github.com/errbit/errbit/files/2260836/build-log.txt)

**Comment by stevecrozz** [comment]
@rud I also invited you to the heroku team so you can check it out.

**Comment by rud** [comment]
Thank you for the invite. I managed to be logged in with a different account, so you'll unfortunately have to invite me once more. Then we should be good to go :+1:

**Comment by rud** [comment]
I think the log output may be in the application log, the rake tasks are probably run as a one-off worker job after the deploy succeeds

**Comment by rud** [comment]
Merging this as it fixes the login issue for PR apps - demo data is still wip :/

**Pull request merged**
