### PR TITLE
Notify about errors in HipChat

### PR DESCRIPTION
**Pull request by maxprokopiev**
Hi guys!

Is there any reason why all errors are silent for HipChat?

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://maxprokopiev-patch-1.23f39035947abfbf29f9f7741cb9c271.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://maxprokopiev-patch-1.23f39035947abfbf29f9f7741cb9c271.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by philippgerard** [comment]
Should be configurable in the Errbit web-interface :)

**Comment by 14113** [comment]
:+1:

**Comment by stevecrozz** [comment]
It sounds like our hipchat users want this. I'll just go with the crowd on this one since I don't use hipchat. Any objections?

**Comment by arthurnn** [comment]
:ship:

**Comment by maxprokopiev** [comment]
awesome, thanks guys %)

**Pull request merged**
