### PR TITLE
Fix Heroku Deployment

### PR DESCRIPTION
**Pull request by Coolguy3289**
Changed the app.json for Heroku deployments to remove mLabs Sandbox as a DB Addon.
Changed app.json and added `MONGODB_URI` config variable allowing user to set a DB Connection String.

Updated Heroku deployment documentation to support MongoDB Atlas free sandbox servers, including screenshots on how to obtain the connection string needed for the quick Heroku deployment.

### CODE REVIEW

**Comment by Coolguy3289** [comment]
This will resolve https://github.com/errbit/errbit/issues/1471

**Comment by stevecrozz** [comment]
Very nice @Coolguy3289 ! I'm sure this will save people some headache in the future. Would you be willing to put screenshots in the ./docs/deployment/ folder and resize them to something smaller like 800x600 or so?

**Comment by Coolguy3289** [comment]
Sure, wasn't sure of any standards you guys used

**Comment by Coolguy3289** [comment]
Alright, I've uploaded the images to the `./docs/deployment/example` folder and remapped them in the heroku.md file.

**Comment by stevecrozz** [comment]
This looks great. Thanks for the effort!

**Pull request merged**
