### PR TITLE
adding readme changes for local install

### PR DESCRIPTION
**Pull request by mtmcfarl**
I followed the steps word for word and got errors because of mongodb not installed / running.  I just made a few simple notes in the README for the local install and updated to the shortcut version of starting a rails server.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://codemancode-readme-changes.23f39035947abfbf29f9f7741cb9c271.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://codemancode-readme-changes.23f39035947abfbf29f9f7741cb9c271.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by stevecrozz** [comment]
Looks like the instructions to install mongo are already here, but above in the 'Installation' section. Was it unclear that those instructions apply to local installation too?

**Comment by mtmcfarl** [comment]
Yeah, because I skipped down to the local install section and there wasn’t any mention of installing mongo.  I think its best even if it is redundant.  I think it makes it more clear, but ultimately its up to y’all.

Thanks!

**Comment by stevecrozz** [comment]
I'll go ahead and merge the change. I need to do some major docs maintenance here pretty soon, so hopefully I can make this all much more clear when I get to it.

**Pull request merged**
