### PR TITLE
Add missing icons for github issue service

### PR DESCRIPTION
**Pull request by felixbuenemann**
These are referenced on the app preferences page.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage. <a href='http://felixbuenemann-add-missing-github-icons.23f39035947abfbf29f9f7741cb9c271.ttrcloud.com' target='_blank'>Click to open.</a>

**Comment by stevecrozz** [comment]
We shouldn't need this because the images should exist here:
https://github.com/errbit/errbit_github_plugin/tree/master/vendor/assets/images

Can you explain a bit more about where they're missing and why they can't be found in the plugin?

**Comment by felixbuenemann** [comment]
I was seeing 404 errors for those images. I know that recent versions of rails/sprockets only add vendor/javascripts and vendor/styles to the load path, which could explain why the images were not found. I'm not sure what's the best way to solve this. I've seen some gems that simply moved all assets to app/assets in the gem.

**Comment by felixbuenemann** [comment]
Hmm, strange. I checked `Rails.application.config.assets.paths`and it lists the vendor/assets/images from the github plugin. I'll investigate further what's going on.

**Comment by felixbuenemann** [comment]
The issue seems to be that images in vendor/assets are no longer precompiled automatically since rails 4.0. So the images would be found in development, but not in production. Probably the easiest fix is to rename vendor folder to app inside the errbit_github_plugin.

**Comment by stevecrozz** [comment]
Thanks very much for figuring this out. I can see what's going on now. My thought is this isn't worth the effort considering we'll be overlapping with: https://github.com/errbit/errbit/issues/784 which is on the road map for 0.4.0. So I'm going to close this one.

**Comment by felixbuenemann** [comment]
Fine with that.

**Pull request closed without merging**
