### PR TITLE
support #371 close issue

### PR DESCRIPTION
**Pull request by mfrederickson**
Via button, not automatic when problem is marked as resolved.  Requires corresponding PRs https://github.com/errbit/errbit_plugin/pull/7 and https://github.com/errbit/errbit_github_plugin/pull/11.

### CODE REVIEW

**Comment by mfrederickson** [comment]
Travis's first job errorred because is couldn' get to the mongdb server https://travis-ci.org/errbit/errbit/jobs/110892229#L387 but the next two succeeded.  It would be nice if I had the permissions to restart a build/test...

**Comment by stevecrozz** [comment]
This seems ready to go except for the conflict. Do you want to add github support by updating the Gemfile? I just published the new errbit_github_plugin version with your changes.

**Comment by mfrederickson** [comment]
I'm not sure what you wanted me to update, but I fetched the upstream and merged it in (after a merge conflict resolution and bundle install).

**Comment by stevecrozz** [comment]
@mfrederickson I think we need to update the Gemfile.lock to pull in the latest version of errbit_github_plugin. Something like 'bundle update errbit_github_plugin' should do the trick.

**Comment by stevecrozz** [comment]
Updating errbit_plugin is probably also in order.

**Comment by stevecrozz** [comment]
Looks good. Thanks very much for doing all this.

**Pull request merged**
