### PR TITLE
Twitter bootstrap

### PR DESCRIPTION
**Pull request by Funfun**
i'v create temporary PR for discussion questions.

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://funfun-twitter-bootstrap.23f39035947abfbf29f9f7741cb9c271.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://funfun-twitter-bootstrap.23f39035947abfbf29f9f7741cb9c271.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by stevecrozz** [comment]
Closing for lack of activity.

**Comment by Funfun** [comment]
@stevecrozz sorry, lost anytime to continue on it.

**Comment by stevecrozz** [comment]
I understand. Thanks for the effort!

**Pull request closed without merging**
