### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by ugorur**
Fix docker health checks port problem

### CODE REVIEW

**Comment by stevecrozz** [comment]
I was not aware that we could use runtime environment variables in the healthcheck command. Is that how this is working?

**Comment by stevecrozz** [comment]
I guess a followup question I have just to understand your use case a little better is why are you changing the default port for running errbit? I had thought users would have no preference on that since its happening inside a container. Did you pass a custom PORT variable at runtime? If so, why? I had thought that would be used only by non docker users.

**Comment by ugorur** [comment]
For your first question, yes you can use any variable or program in health check if it's in your runing container.

I create a docker swarm service with errbit image and I don't want to expose my errbit url to any other services so I create different network and auto configuration tool for connected networks. 

If any of my service detecte errbil network and givin alias for errbit service, it's add errbit variable automatically to environment variables and create new app for given service to errbit if it's not exist.

I just don't want to add extra 8080 port to variable settings so I started my errbit service with 80 port but it didn't start so I change docker file.

Sorry for the unnecessarily long and bad answer :)

**Comment by stevecrozz** [comment]
Thanks for the explanation! This seems fine to me.

**Pull request merged**
