### PR TITLE
sort apps by name

### PR DESCRIPTION
**Pull request by lucianosousa**

### CODE REVIEW

**Comment by stevecrozz** [comment]
Is this intended as a performance improvement so that we can avoid loading all the apps just to sort them in ruby?

**Comment by lucianosousa** [comment]
also, better to find projects in the list when we have a lot of them.

**Comment by stevecrozz** [comment]
This makes sense. I just can't tell what 'all.sort' used to do. It looks like it would just use the default spaceship operator (<=>) to sort the mongoid documents which seems like a meaningless no-op at best.

**Comment by lucianosousa** [comment]
I like this approach because it uses the mongoid api. cleaner and elegant result.
:)

if you want I can try this idea you have, but I really don't recommend.

**Comment by stevecrozz** [comment]
No this is fine, I don't have an idea I was just trying to figure out the point of the existing code. But I believe it has no point.

**Comment by lucianosousa** [comment]
:+1:

**Pull request merged**
